import {NextRequest,NextResponse} from 'next/server';
import {requireAdmin,AccessError,safeUrl} from '@/lib/admin';
import {sameOrigin} from '@/lib/server';
import {validateProduct} from '@/lib/product-validation.mjs';
import {stripeClient} from '@/lib/payments';
const headers={'Cache-Control':'private, no-store'};
function failure(e:unknown){return NextResponse.json({error:e instanceof AccessError?e.message:e instanceof Error?e.message:'Unable to complete the request.'},{status:e instanceof AccessError?e.status:400,headers})}
export async function GET(req:NextRequest){try{const {db,profile}=await requireAdmin();const resource=req.nextUrl.searchParams.get('resource')||'dashboard',page=Math.max(0,Number(req.nextUrl.searchParams.get('page'))||0),q=(req.nextUrl.searchParams.get('q')||'').replace(/[,%()]/g,'').slice(0,100);let result;
 if(resource==='dashboard'||resource==='analytics'){const [metrics,orders,low]=await Promise.all([db.rpc('admin_metrics'),db.from('orders').select('*').order('created_at',{ascending:false}).limit(8),db.from('variants').select('id,title,stock,reserved_stock,products(title)').eq('active',true).order('stock').limit(100)]);if(metrics.error||orders.error||low.error)throw Error('Apply the owner-platform migration to load dashboard data.');return NextResponse.json({metrics:metrics.data,orders:orders.data,low_stock:low.data?.filter(x=>x.stock-x.reserved_stock<=3).slice(0,10),profile},{headers})}
 if(resource==='products'){let query=db.from('products').select('*,variants(*)',{count:'exact'}).is('deleted_at',null).order('created_at',{ascending:false});if(q)query=query.ilike('title','%'+q+'%');result=await query.range(page*50,page*50+49)}
 else if(resource==='inventory'){let query=db.from('variants').select('*,products(title,images,deleted_at)',{count:'exact'}).order('stock');if(q)query=query.ilike('sku','%'+q+'%');result=await query.range(page*50,page*50+49)}
 else if(resource==='orders'){let query=db.from('orders').select('*,order_items(*)',{count:'exact'}).order('created_at',{ascending:false});if(q)query=query.or(`order_number.ilike.%${q}%,email.ilike.%${q}%`);result=await query.range(page*50,page*50+49)}
 else if(resource==='customers'){let query=db.from('users').select('*',{count:'exact'}).order('created_at',{ascending:false});if(q)query=query.ilike('email','%'+q+'%');result=await query.range(page*50,page*50+49);if(result.data?.length){const ids=result.data.map(x=>x.auth_id),emails=result.data.map(x=>x.email);const orders=await db.from('orders').select('id,order_number,user_id,email,payment_status,total_price,created_at,order_status').or(`user_id.in.(${ids.join(',')}),email.in.(${emails.map(x=>'"'+x.replaceAll('"','')+'"').join(',')})`).limit(10000);result.data=result.data.map(u=>({...u,orders:(orders.data||[]).filter(o=>o.user_id===u.auth_id||o.email===u.email)}))}}
 else if(resource==='discounts')result=await db.from('discounts').select('*').order('created_at',{ascending:false});
 else if(resource==='content')result=await db.from('site_content').select('*');
 else if(resource==='settings')return NextResponse.json({profile,connections:{supabase:!!process.env.NEXT_PUBLIC_SUPABASE_URL,stripe:!!process.env.STRIPE_SECRET_KEY,webhook:!!process.env.STRIPE_WEBHOOK_SECRET,checkout:process.env.ENABLE_CHECKOUT!=='false',shipping:!!process.env.STRIPE_SHIPPING_RATE_ID},data:(await db.from('site_content').select('*').eq('key','store')).data||[]},{headers});
 else throw new AccessError(404,'Unknown dashboard section.');
 if(result?.error)throw Error('Unable to load store data. Check that the platform migrations are applied.');return NextResponse.json({data:result?.data||[],count:result?.count,profile},{headers});
 }catch(e){return failure(e)}}
export async function POST(req:NextRequest){if(!sameOrigin(req))return NextResponse.json({error:'Invalid request.'},{status:403});try{const {db,user}=await requireAdmin();const b=await req.json();let result:any;
 if(b.action==='save_product'){const product=validateProduct(b.product);if(b.id!=null&&!Number.isSafeInteger(b.id))throw Error('Invalid product ID');result=await db.rpc('admin_save_product',{p_id:b.id||null,p_data:product})}
 else if(b.action==='duplicate_product'){const {data:p,error}=await db.from('products').select('*,variants(*)').eq('id',b.id).single();if(error||!p)throw Error('Product not found');const copy=validateProduct({...p,title:p.title+' (copy)',handle:p.handle+'-copy-'+crypto.randomUUID().slice(0,6),visible:false,variants:p.variants.map((v:any)=>({...v,id:null,stock:0,active:false}))});result=await db.rpc('admin_save_product',{p_id:null,p_data:copy})}
 else if(b.action==='hide_product'||b.action==='delete_product'){result=await db.from('products').update(b.action==='delete_product'?{visible:false,deleted_at:new Date().toISOString()}:{visible:!b.hidden}).eq('id',b.id)}
 else if(b.action==='inventory'){if(!Number.isSafeInteger(b.variant)||!Number.isInteger(b.delta)||Math.abs(b.delta)>100000||b.active!=null&&typeof b.active!=='boolean')throw Error('Enter a valid stock adjustment');result=await db.rpc('admin_adjust_inventory',{p_variant:b.variant,p_delta:b.delta,p_active:b.active??null})}
 else if(b.action==='order'){if(!['processing','shipped','delivered','cancelled'].includes(b.status))throw Error('Invalid shipping status');const {data:o}=await db.from('orders').select('payment_status').eq('id',b.id).single();if(!o)throw Error('Order not found');if(['shipped','delivered'].includes(b.status)&&o.payment_status!=='paid')throw Error('Payment must be confirmed before fulfillment.');if(b.tracking_url&&!safeUrl(b.tracking_url))throw Error('Tracking links must use HTTPS.');result=await db.from('orders').update({order_status:b.status,shipping_status:b.status,tracking_number:String(b.tracking_number||'').slice(0,150),tracking_url:b.tracking_url||null}).eq('id',b.id)}
 else if(b.action==='discount'){const code=String(b.code||'').toUpperCase().trim();if(!/^[A-Z0-9_-]{3,30}$/.test(code)||!Number.isInteger(b.percent)||b.percent<1||b.percent>90)throw Error('Use a 3–30 character coupon code and a discount of 1–90%.');if(!process.env.STRIPE_SECRET_KEY)throw new AccessError(503,'Connect Stripe before creating a redeemable coupon.');const end=b.expires_at?Math.floor(new Date(b.expires_at).getTime()/1000):undefined;if(end&&(!Number.isFinite(end)||end<Date.now()/1000))throw Error('Expiry must be in the future.');const stripe=stripeClient();const coupon=await stripe.coupons.create({name:String(b.name||code).slice(0,80),duration:'once',percent_off:b.percent,...(end?{redeem_by:end}:{})},{idempotencyKey:'kashish-coupon-'+code});result=await db.from('discounts').insert({name:String(b.name||code).slice(0,80),code,percent:b.percent,collection:b.collection||null,stripe_coupon_id:coupon.id,expires_at:end?new Date(end*1000).toISOString():null})}
 else if(b.action==='discount_active'){result=await db.from('discounts').update({active:!!b.active}).eq('id',b.id)}
 else if(b.action==='content'){if(!['hero','homepage','store'].includes(b.key)||!b.value||typeof b.value!=='object'||JSON.stringify(b.value).length>50000)throw Error('Invalid website content.');result=await db.from('site_content').upsert({key:b.key,value:b.value,updated_at:new Date().toISOString()})}
 else throw Error('Unknown action');
 if(result?.error){if(result.error.code==='23505')throw Error('This URL handle or coupon code is already in use.');throw Error(result.error.message||'Unable to save changes.')}
 await db.from('audit_logs').insert({actor_id:user.id,action:b.action,target:String(b.id||result?.data||b.key||'')});return NextResponse.json({success:true,id:result?.data},{headers});
 }catch(e){return failure(e)}}
