'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {useRouter} from 'next/navigation';
import {Eye,EyeOff,ArrowRight,Mail,ShieldCheck} from 'lucide-react';
import {browserDatabase} from '@/lib/supabase/browser';
export function AddressFields({defaults={},required=true}:{defaults?:any;required?:boolean}){return <><label>Country<select name="country" required={required} defaultValue={defaults.country||'United States'}>{['United States','Canada','United Kingdom','Pakistan','United Arab Emirates','Australia','India','Saudi Arabia','Other'].map(c=><option key={c}>{c}</option>)}</select></label><label className="span-two">Street address<input name="street" autoComplete="address-line1" required={required} defaultValue={defaults.street||''}/></label><label>Apartment / suite (optional)<input name="apartment" autoComplete="address-line2" defaultValue={defaults.apartment||''}/></label><label>City<input name="city" autoComplete="address-level2" required={required} defaultValue={defaults.city||''}/></label><label>State / region<input name="state" autoComplete="address-level1" required={required} defaultValue={defaults.state||''}/></label><label>ZIP / postal code<input name="postal_code" autoComplete="postal-code" required={required} defaultValue={defaults.postal_code||''}/></label></>}
export const addressFrom=(f:FormData)=>Object.fromEntries(['country','street','apartment','city','state','postal_code'].map(k=>[k,String(f.get(k)||'').trim()]));
export function PasswordField({label='Password',name='password',confirm=false}:{label?:string;name?:string;confirm?:boolean}){const [show,setShow]=useState(false);return <label>{label}<div className="password-input"><input type={show?'text':'password'} name={name} autoComplete={confirm?'new-password':'current-password'} required minLength={8} maxLength={128}/><button type="button" aria-label={show?'Hide password':'Show password'} onClick={()=>setShow(!show)}>{show?<EyeOff size={18}/>:<Eye size={18}/>}</button></div></label>}
export default function CustomerAuth({mode}:{mode:'login'|'signup'|'forgot-password'|'reset-password'}){const router=useRouter();const [message,setMessage]=useState(''),[busy,setBusy]=useState(false),[complete,setComplete]=useState(false);const signup=mode==='signup',reset=mode==='reset-password',forgot=mode==='forgot-password';const title=signup?'Make yourself at home.':forgot?'A fresh start.':reset?'Choose a new password.':'Welcome back.';
 useEffect(()=>{if(new URLSearchParams(location.search).get('error')==='verification')setMessage('This verification link has expired or is invalid. Request a new password reset link or sign in again.')},[]);
 async function google(){const remember=(document.querySelector('input[name=remember]') as HTMLInputElement|null)?.checked;document.cookie='ka_remember='+(remember?'1':'0')+'; Path=/; SameSite=Lax'+(remember?'; Max-Age=31536000':'');const db=browserDatabase();if(!db){setMessage('Account services have not been connected yet. Please contact Kashish Apparel for assistance.');return}setBusy(true);const {error}=await db.auth.signInWithOAuth({provider:'google',options:{redirectTo:location.origin+'/auth/callback?next=/account'}});if(error){setMessage(error.message);setBusy(false)}}
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setMessage('');const f=new FormData(e.currentTarget),db=browserDatabase();try{if(!db)throw Error('Account services have not been connected yet. Please contact customer care.');const email=String(f.get('email')||'').trim(),password=String(f.get('password')||'');if((signup||reset)&&password!==f.get('confirm_password'))throw Error('Your passwords do not match.');if(mode==='login'||signup){const remember=f.get('remember')==='on';document.cookie='ka_remember='+(remember?'1':'0')+'; Path=/; SameSite=Lax'+(remember?'; Max-Age=31536000':'')}
 if(signup){const {data,error}=await db.auth.signUp({email,password,options:{emailRedirectTo:location.origin+'/auth/callback?next=/account',data:{first_name:f.get('first_name'),last_name:f.get('last_name'),phone:f.get('phone'),address:addressFrom(f),date_of_birth:f.get('date_of_birth')||null,gender_preference:f.get('gender_preference')||null,marketing_consent:f.get('marketing')==='on'}}});if(error)throw error;setComplete(true);setMessage('Check your inbox to verify your email, then sign in to your Kashish account.');if(data.session)router.push('/account')}
 else if(forgot){const {error}=await db.auth.resetPasswordForEmail(email,{redirectTo:location.origin+'/auth/callback?next=/reset-password'});if(error)throw error;setComplete(true);setMessage('If an account exists for that email, you’ll receive a secure password reset link.')}
 else if(reset){const {data}=await db.auth.getUser();if(!data.user)throw Error('Open the secure reset link from your email first.');const {error}=await db.auth.updateUser({password});if(error)throw error;setComplete(true);setMessage('Your password has been updated. You can now continue to your account.')}
 else{const {error}=await db.auth.signInWithPassword({email,password});if(error)throw error;const next=new URLSearchParams(location.search).get('next');router.push(next?.startsWith('/')&&!next.startsWith('//')&&!next.includes('\\')?next:'/account');router.refresh()}
 }catch(e){setMessage((e as Error).message)}finally{setBusy(false)}}
 return <section className={'auth-shell '+(signup?'wide':'')}><div className="auth-intro"><p className="eyebrow">YOUR KASHISH EXPERIENCE</p><h1>{title}</h1><p>{signup?'Save your favourites, discover new collections, and follow every order.':forgot?'Enter your email and we’ll send a secure reset link.':'Your favourite pieces and special moments, all in one place.'}</p></div>{complete?<div className="auth-confirmation"><Mail size={32}/><p role="status">{message}</p><Link className="button" href={reset?'/account':'/login'}>{reset?'MY ACCOUNT':'RETURN TO LOGIN'} <ArrowRight size={16}/></Link></div>:<><form className="customer-form" onSubmit={submit}><div className={signup?'form-grid':''}>{signup&&<><label>First name<input name="first_name" autoComplete="given-name" required maxLength={80}/></label><label>Last name<input name="last_name" autoComplete="family-name" required maxLength={80}/></label></>}{!reset&&<label className={signup?'span-two':''}>Email address<input name="email" type="email" autoComplete="email" required maxLength={254}/></label>}{!forgot&&<PasswordField label={reset?'New password':'Password'} confirm={signup||reset}/>} {(signup||reset)&&<PasswordField name="confirm_password" label="Confirm password" confirm/>}{signup&&<><label className="span-two">Phone number<input name="phone" type="tel" autoComplete="tel" required maxLength={40}/></label><h2 className="form-section span-two">Your address</h2><AddressFields/><h2 className="form-section span-two">A little more about you <small>Optional</small></h2><label>Date of birth<input name="date_of_birth" type="date" max={new Date().toISOString().slice(0,10)}/></label><label>Shopping preference<select name="gender_preference"><option value="">Prefer not to say</option><option>Womenswear</option><option>Menswear</option><option>Both</option></select></label><label className="checkbox-label span-two"><input name="marketing" type="checkbox"/> Send me new collections and exclusive offers.</label></>}</div>{!forgot&&!reset&&<div className="auth-options"><label className="checkbox-label"><input type="checkbox" name="remember"/> Remember me</label><Link href="/forgot-password">Forgot password?</Link></div>}<button className="button full" disabled={busy}>{busy?'PLEASE WAIT…':signup?'CREATE ACCOUNT':forgot?'SEND RESET LINK':reset?'UPDATE PASSWORD':'LOGIN'} <ArrowRight size={17}/></button>{message&&<p role="alert" className="form-message">{message}</p>}</form>{!forgot&&!reset&&<><div className="auth-divider"><span>OR</span></div><button className="google-button" disabled={busy} onClick={google}><span className="google-g">G</span> Continue with Google</button><p className="auth-switch">{signup?'Already have an account?':'New to Kashish?'} <Link href={signup?'/login':'/signup'}>{signup?'Sign in':'Create an account'}</Link></p></>}</>}<p className="auth-privacy"><ShieldCheck size={15}/> Your details are protected. <Link href="/privacy">Privacy policy</Link></p></section>
}
