'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {AnimatePresence,motion,useReducedMotion} from 'framer-motion';
import {Menu,Search,UserRound,ShoppingBag,X,ArrowUpRight,Heart} from 'lucide-react';
import {women} from '@/lib/catalog';
export default function LuxuryHeader({home,count,wishlist,onSearch,onBag}:{home:boolean;count:number;wishlist:number;onSearch:()=>void;onBag:()=>void}){
 const [scrolled,setScrolled]=useState(false),[open,setOpen]=useState(false);const reduced=useReducedMotion();
 useEffect(()=>{const update=()=>setScrolled(window.scrollY>40);update();window.addEventListener('scroll',update,{passive:true});return()=>window.removeEventListener('scroll',update)},[]);
 useEffect(()=>{if(!open)return;const previous=document.activeElement as HTMLElement;const old=document.body.style.overflow;document.body.style.overflow='hidden';const timer=setTimeout(()=>document.querySelector<HTMLButtonElement>('.navigation-close')?.focus(),0);const key=(e:KeyboardEvent)=>{if(e.key==='Escape')setOpen(false);if(e.key==='Tab'){const nodes=Array.from(document.querySelectorAll<HTMLElement>('.navigation-panel a,.navigation-panel button'));const first=nodes[0],last=nodes.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus()}}};document.addEventListener('keydown',key);return()=>{clearTimeout(timer);document.body.style.overflow=old;document.removeEventListener('keydown',key);previous?.focus()}},[open]);
 return <><header className={`luxury-header ${home&&!scrolled?'over-hero':'on-white'}`}><div className="luxury-masthead"><button className="header-menu" aria-label="Open navigation" aria-expanded={open} onClick={()=>setOpen(true)}><Menu size={23}/></button><nav className="luxury-nav" aria-label="Main navigation">{[['New Arrivals','new-arrivals'],['Wedding','wedding-formals'],['Sarees','designer-sarees'],['Women','women'],['Men','men']].map(([name,slug])=><Link key={slug} href={'/collections/'+slug}>{name}</Link>)}</nav><motion.div initial={reduced?false:{opacity:0}} animate={{opacity:1}} transition={{duration:1}} className="official-logo"><Link href="/" aria-label="Kashish Apparel home"><img src="/kashish-logo.png" alt="Kashish Apparel official KA calligraphy logo" width={170} height={170}/></Link></motion.div><div className="luxury-actions"><button aria-label="Search products" onClick={onSearch}><Search size={21}/></button><Link className="desktop-account" href="/account" aria-label="My account"><UserRound size={21}/></Link><motion.button aria-label={`Shopping bag, ${count} items`} onClick={onBag} animate={{scale:[1,1.08,1]}} key={count} transition={{duration:.35}}><ShoppingBag size={21}/><sup>{count}</sup></motion.button></div></div></header><AnimatePresence>{open&&<motion.div className="navigation-overlay" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} onClick={()=>setOpen(false)}><motion.section role="dialog" aria-modal="true" aria-label="Shop navigation" className="navigation-panel" initial={reduced?false:{x:'-100%'}} animate={{x:0}} exit={{x:'-100%'}} transition={{duration:.35}} onClick={e=>e.stopPropagation()}><div className="navigation-title"><span>KASHISH APPAREL</span><button className="navigation-close" aria-label="Close navigation" onClick={()=>setOpen(false)}><X/></button></div><p className="eyebrow">EXPLORE THE COLLECTIONS</p>{[['New Arrivals','new-arrivals'],...women,['Men','men'],['Accessories','accessories'],['Sale','sale']].map(([name,slug])=><Link key={slug} href={'/collections/'+slug} onClick={()=>setOpen(false)}>{name}<ArrowUpRight size={18}/></Link>)}<div className="navigation-utilities"><Link href="/wishlist" onClick={()=>setOpen(false)}><Heart size={17}/> Wishlist ({wishlist})</Link><Link href="/account" onClick={()=>setOpen(false)}><UserRound size={17}/> My account</Link><Link href="/contact" onClick={()=>setOpen(false)}>Contact & styling advice</Link></div></motion.section></motion.div>}</AnimatePresence></>;
}
