'use client';
import {useEffect,useRef,useState} from 'react';
import Link from 'next/link';
import {motion,useReducedMotion} from 'framer-motion';
import {X,ShoppingBag,Check,ArrowUpRight} from 'lucide-react';
import {Product,photo,money} from '@/lib/catalog';
export default function QuickView({p,close,add}:{p:Product;close:()=>void;add:(p:Product,v:number,n:number)=>void}){const [variant,setVariant]=useState(p.variants.find(v=>v.available)?.id||p.variants[0].id),[added,setAdded]=useState(false),[live,setLive]=useState<{id:number;price:string;available:boolean}[]>([]);const reduced=useReducedMotion(),timer=useRef<ReturnType<typeof setTimeout>|null>(null);const v={...p.variants.find(v=>v.id===variant)!,...live.find(v=>v.id===variant)};
 useEffect(()=>{const controller=new AbortController();fetch('/api/inventory?product='+p.id,{signal:controller.signal}).then(r=>r.json()).then(d=>setLive(d.variants||[])).catch(()=>{});const old=document.body.style.overflow,previous=document.activeElement as HTMLElement;document.body.style.overflow='hidden';document.querySelector<HTMLButtonElement>('.quick-close')?.focus();const key=(e:KeyboardEvent)=>{if(e.key==='Escape')close();if(e.key==='Tab'){const all=Array.from(document.querySelectorAll<HTMLElement>('.quick-modal button:not(:disabled),.quick-modal a'));const first=all[0],last=all.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus()}}};document.addEventListener('keydown',key);return()=>{controller.abort();if(timer.current)clearTimeout(timer.current);document.body.style.overflow=old;document.removeEventListener('keydown',key);previous?.focus()}},[p.id]);
 return <div className="quick-overlay" onClick={close}><motion.section className="quick-modal" role="dialog" aria-modal="true" aria-label={'Quick view: '+p.title} initial={reduced?false:{opacity:0,y:20}} animate={{opacity:1,y:0}} onClick={e=>e.stopPropagation()}><button className="quick-close" aria-label="Close quick view" onClick={close}><X/></button><img className="quick-photo" src={photo(p,900)} alt={p.title}/><div className="quick-copy"><p className="eyebrow">THE KASHISH EDIT</p><h2>{p.title}</h2><p className="price">{money(v.price)} <small>USD</small></p><p>Thoughtfully selected. Beautifully yours.</p><div className="size-label"><span>SIZE</span><Link href="/size-guide" onClick={close}>Size guide</Link></div><div className="sizes">{p.variants.map(x=>{const choice={...x,...live.find(l=>l.id===x.id)};return <button key={x.id} disabled={!choice.available||added} className={variant===x.id?'selected':''} onClick={()=>setVariant(x.id)}>{x.title==='Default Title'?'See product sizing':x.title}</button>})}</div>{p.variants.every(x=>x.title==='Default Title')&&<p className="sizing-note">Please check the size in the product photography or ask our stylist to confirm your fit.</p>}<motion.button className="button full" disabled={!v.available||added} whileTap={{scale:.98}} onClick={()=>{setAdded(true);timer.current=setTimeout(()=>{add(p,v.id,1);close()},450)}}>{added?<><Check size={18}/> ADDED TO BAG</>:<>{v.available?'ADD TO BAG':'SOLD OUT'} <ShoppingBag size={18}/></>}</motion.button><Link className="text-link" href={'/products/'+p.handle} onClick={close}>Explore all details <ArrowUpRight size={16}/></Link><p className="quick-policy">All sales are final. Complimentary US shipping on orders $200+.</p></div></motion.section></div>
}
