import {PGlite} from '@electric-sql/pglite';
import {readFile} from 'node:fs/promises';
import assert from 'node:assert/strict';
import test from 'node:test';
import {createHash,randomUUID} from 'node:crypto';
const db=new PGlite();
await db.exec(`create role anon;create role authenticated;create role service_role bypassrls;create schema auth;create table auth.users(id uuid primary key);create function auth.uid() returns uuid language sql as $$select nullif(current_setting('request.user_id',true),'')::uuid$$;create function auth.jwt() returns jsonb language sql as $$select coalesce(nullif(current_setting('request.jwt',true),''),'{}')::jsonb$$;grant usage on schema auth to anon,authenticated;grant execute on all functions in schema auth to anon,authenticated;`);
await db.exec(await readFile('supabase/schema.sql','utf8'));
// Existing records and a pending legacy checkout must survive migration.
const owner='11111111-1111-1111-1111-111111111111',other='22222222-2222-2222-2222-222222222222';
await db.query('insert into auth.users values($1),($2)',[owner,other]);
await db.exec("insert into products(id,handle,title) values(1,'test-outfit','Test outfit');insert into variants(id,product_id,title,price,stock,active) values(10,1,'Small',13000,5,true)");
const legacy=(await db.query('select reserve_order($1::jsonb,$2::uuid) as result',[JSON.stringify([{variant:10,quantity:1}]),owner])).rows[0].result;
await db.exec(await readFile('supabase/migrations/20260916_checkout_v2.sql','utf8'));
const hash=s=>createHash('sha256').update(s).digest('hex');
const inventory=async()=>(await db.query('select stock,reserved_stock from variants where id=10')).rows[0];
const reserve=async(key=randomUUID(),quantity=1,user=owner)=>(await db.query('select reserve_checkout($1::jsonb,$2::uuid,$3,$4) as result',[JSON.stringify([{variant:10,quantity}]),user,hash(key),hash(JSON.stringify({quantity}))])).rows[0].result;
const settle=async(id,paid,session='cs_test_example',total=13000)=>db.query('select settle_checkout($1,$2,$3,$4,$5,$6,$7)',[id,session,paid,'owner@example.test',total,null,'Test Customer']);
let order,key=randomUUID();
await test('additive migration preserves existing pending orders and inventory',async()=>{assert.deepEqual(await inventory(),{stock:4,reserved_stock:0});assert.equal((await db.query('select inventory_mode from orders where id=$1',[legacy.id])).rows[0].inventory_mode,'legacy');await db.query('select finish_order($1,false,null,null,null)',[legacy.id]);assert.equal((await inventory()).stock,5)});
await test('checkout holds availability without reducing physical stock',async()=>{order=await reserve(key,2);assert.deepEqual(await inventory(),{stock:5,reserved_stock:2});assert.equal(order.items[0].price,13000)});
await test('retrying the same checkout is idempotent; different bag or customer is rejected',async()=>{assert.equal((await reserve(key,2)).id,order.id);assert.deepEqual(await inventory(),{stock:5,reserved_stock:2});await assert.rejects(reserve(key,1));await assert.rejects(reserve(key,2,other))});
await test('concurrent checkout attempts cannot oversell reserved availability',async()=>{const result=await Promise.allSettled([reserve(randomUUID(),3),reserve(randomUUID(),3)]);assert.equal(result.filter(r=>r.status==='fulfilled').length,1);const extra=result.find(r=>r.status==='fulfilled').value;await settle(extra.id,false,'cs_extra');assert.deepEqual(await inventory(),{stock:5,reserved_stock:2})});
await test('invalid payment amount rolls back all inventory changes',async()=>{await assert.rejects(settle(order.id,true,'cs_test_paid',1));assert.deepEqual(await inventory(),{stock:5,reserved_stock:2})});
await test('verified payment reduces stock once and stores the requested order fields',async()=>{await settle(order.id,true,'cs_test_paid',28000);await settle(order.id,true,'cs_test_paid',28000);assert.deepEqual(await inventory(),{stock:3,reserved_stock:0});const row=(await db.query('select * from orders where id=$1',[order.id])).rows[0];assert.equal(row.customer_id,owner);assert.match(row.order_number,/^KA-/);assert.equal(row.items.length,1);assert.equal(row.total_price,28000);assert.equal(row.payment_status,'paid');assert.equal(row.order_status,'processing')});
await test('expired sessions release only reserved stock and are idempotent',async()=>{const cancelled=await reserve();await settle(cancelled.id,false,'cs_cancelled');await settle(cancelled.id,false,'cs_cancelled');assert.deepEqual(await inventory(),{stock:3,reserved_stock:0});await assert.rejects(settle(cancelled.id,true,'cs_cancelled'));assert.deepEqual(await inventory(),{stock:3,reserved_stock:0})});
await test('wrong session cannot alter a paid order',async()=>{await assert.rejects(settle(order.id,true,'cs_other',28000))});
await test('RLS and service-only checkout functions remain enforced',async()=>{await db.exec('set role authenticated');await db.query("select set_config('request.user_id',$1,false)",[other]);assert.equal((await db.query('select * from orders')).rows.length,0);await assert.rejects(reserve());await assert.rejects(db.exec('update variants set stock=999'));await db.exec('reset role');await db.exec('set role anon');await assert.rejects(db.exec('select * from orders'));await assert.rejects(db.exec('select * from contact_messages'));await db.exec('reset role')});
await db.close();
