import {PGlite} from '@electric-sql/pglite';
import {readFile} from 'node:fs/promises';
import assert from 'node:assert/strict';
import test from 'node:test';
const db=new PGlite();
await db.exec(`create role anon;create role authenticated;create role service_role bypassrls;create schema auth;create table auth.users(id uuid primary key);create function auth.uid() returns uuid language sql as $$select nullif(current_setting('request.user_id',true),'')::uuid$$;create function auth.jwt() returns jsonb language sql as $$select coalesce(nullif(current_setting('request.jwt',true),''),'{}')::jsonb$$;grant usage on schema auth to anon,authenticated;grant execute on all functions in schema auth to anon,authenticated;`);
await db.exec(await readFile('supabase/schema.sql','utf8'));
const owner='11111111-1111-1111-1111-111111111111',other='22222222-2222-2222-2222-222222222222';
await db.query('insert into auth.users values($1),($2)',[owner,other]);
await db.exec("insert into products(id,handle,title) values(1,'test-outfit','Test outfit');insert into variants(id,product_id,title,price,stock,active) values(10,1,'Small',13000,5,true)");
const stock=async()=>(await db.query('select stock from variants where id=10')).rows[0].stock;
const reserve=async(qty=1)=>(await db.query('select reserve_order($1::jsonb,$2::uuid) as result',[JSON.stringify([{variant:10,quantity:qty}]),owner])).rows[0].result;
const finish=async(id,paid)=>db.query('select finish_order($1,$2,$3,$4,$5)',[id,paid,'owner@example.test',13000,null]);
let paidOrder;
await test('reserves inventory and ignores client pricing',async()=>{paidOrder=await reserve(2);assert.equal(await stock(),3);assert.equal(paidOrder.items[0].price,13000)});
await test('overselling fails atomically without creating an order',async()=>{const before=(await db.query('select count(*) as n from orders')).rows[0].n;await assert.rejects(reserve(4));assert.equal(await stock(),3);assert.equal((await db.query('select count(*) as n from orders')).rows[0].n,before)});
await test('duplicate paid webhooks do not decrement stock again',async()=>{await finish(paidOrder.id,true);await finish(paidOrder.id,true);assert.equal(await stock(),3);assert.equal((await db.query('select status from orders where id=$1',[paidOrder.id])).rows[0].status,'paid')});
await test('expired order restores stock once',async()=>{const o=await reserve();assert.equal(await stock(),2);await finish(o.id,false);await finish(o.id,false);assert.equal(await stock(),3)});
await test('customer sees own order but cannot read another customer order or modify stock',async()=>{await db.exec('set role authenticated');await db.query("select set_config('request.user_id',$1,false)",[other]);assert.equal((await db.query('select * from orders')).rows.length,0);await db.query("select set_config('request.user_id',$1,false)",[owner]);assert.equal((await db.query('select * from orders')).rows.length,2);await assert.rejects(db.exec('update variants set stock=999'));await assert.rejects(db.query('select reserve_order($1::jsonb,$2::uuid)',[JSON.stringify([{variant:10,quantity:1}]),other]));await assert.rejects(db.exec('select * from contact_messages'));await db.exec('reset role')});
await test('anonymous user cannot read orders or customer submissions',async()=>{await db.exec('set role anon');await assert.rejects(db.exec('select * from orders'));await assert.rejects(db.exec('select * from newsletter_subscribers'));await assert.rejects(db.exec('select * from contact_messages'));assert.equal((await db.query('select * from products')).rows.length,1);await db.exec('reset role')});
await test('rate limiter blocks excessive requests',async()=>{for(let i=0;i<5;i++)assert.equal((await db.query("select consume_rate_limit('test',5) as allowed")).rows[0].allowed,true);assert.equal((await db.query("select consume_rate_limit('test',5) as allowed")).rows[0].allowed,false)});
await db.close();
